//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTOS
    {
        public DEPARTAMENTOS()
        {
            this.CLIENTES = new HashSet<CLIENTES>();
        }
    
        public int id_depart { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
    }
}
