//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS
    {
        public FACTURAS()
        {
            this.FACTURAS_DETALLE = new HashSet<FACTURAS_DETALLE>();
        }
    
        public int id_factura { get; set; }
        public Nullable<int> fk_id_cliente { get; set; }
        public string clientes_nombre { get; set; }
        public string clientes_direccion { get; set; }
        public string clientes_departamento { get; set; }
        public string clientes_registro { get; set; }
        public string clientes_num_nit { get; set; }
        public string clientes_giro { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> total { get; set; }
        public string total_letras { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual ICollection<FACTURAS_DETALLE> FACTURAS_DETALLE { get; set; }
    }
}
