//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS_DETALLE
    {
        public int id_factura_detalle { get; set; }
        public Nullable<int> fk_id_factura { get; set; }
        public Nullable<int> fk_id_articulo { get; set; }
        public string articulos_descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
        public virtual FACTURAS FACTURAS { get; set; }
    }
}
