//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string contrasena { get; set; }
        public string rol { get; set; }
        public string nivel_acceso { get; set; }
    }
}
